// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: depart.proto

package com.depart.grpc;

/**
 * Protobuf type {@code com.depart.grpc.DepartResponse}
 */
public  final class DepartResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.depart.grpc.DepartResponse)
    DepartResponseOrBuilder {
  // Use DepartResponse.newBuilder() to construct.
  private DepartResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DepartResponse() {
    id_ = 0;
    departname_ = "";
    priority_ = 0;
    parentid_ = 0;
    statusId_ = 0;
    depart_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DepartResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            departname_ = s;
            break;
          }
          case 24: {

            priority_ = input.readInt32();
            break;
          }
          case 32: {

            parentid_ = input.readInt32();
            break;
          }
          case 40: {

            statusId_ = input.readInt32();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              depart_ = new java.util.ArrayList<com.depart.grpc.Depart>();
              mutable_bitField0_ |= 0x00000020;
            }
            depart_.add(
                input.readMessage(com.depart.grpc.Depart.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        depart_ = java.util.Collections.unmodifiableList(depart_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.depart.grpc.DepartOuterClass.internal_static_com_depart_grpc_DepartResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.depart.grpc.DepartOuterClass.internal_static_com_depart_grpc_DepartResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.depart.grpc.DepartResponse.class, com.depart.grpc.DepartResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int DEPARTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object departname_;
  /**
   * <code>string departname = 2;</code>
   */
  public java.lang.String getDepartname() {
    java.lang.Object ref = departname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departname_ = s;
      return s;
    }
  }
  /**
   * <code>string departname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDepartnameBytes() {
    java.lang.Object ref = departname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      departname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIORITY_FIELD_NUMBER = 3;
  private int priority_;
  /**
   * <code>int32 priority = 3;</code>
   */
  public int getPriority() {
    return priority_;
  }

  public static final int PARENTID_FIELD_NUMBER = 4;
  private int parentid_;
  /**
   * <code>int32 parentid = 4;</code>
   */
  public int getParentid() {
    return parentid_;
  }

  public static final int STATUS_ID_FIELD_NUMBER = 5;
  private int statusId_;
  /**
   * <code>int32 status_id = 5;</code>
   */
  public int getStatusId() {
    return statusId_;
  }

  public static final int DEPART_FIELD_NUMBER = 6;
  private java.util.List<com.depart.grpc.Depart> depart_;
  /**
   * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
   */
  public java.util.List<com.depart.grpc.Depart> getDepartList() {
    return depart_;
  }
  /**
   * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
   */
  public java.util.List<? extends com.depart.grpc.DepartOrBuilder> 
      getDepartOrBuilderList() {
    return depart_;
  }
  /**
   * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
   */
  public int getDepartCount() {
    return depart_.size();
  }
  /**
   * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
   */
  public com.depart.grpc.Depart getDepart(int index) {
    return depart_.get(index);
  }
  /**
   * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
   */
  public com.depart.grpc.DepartOrBuilder getDepartOrBuilder(
      int index) {
    return depart_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getDepartnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, departname_);
    }
    if (priority_ != 0) {
      output.writeInt32(3, priority_);
    }
    if (parentid_ != 0) {
      output.writeInt32(4, parentid_);
    }
    if (statusId_ != 0) {
      output.writeInt32(5, statusId_);
    }
    for (int i = 0; i < depart_.size(); i++) {
      output.writeMessage(6, depart_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getDepartnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, departname_);
    }
    if (priority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, priority_);
    }
    if (parentid_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, parentid_);
    }
    if (statusId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, statusId_);
    }
    for (int i = 0; i < depart_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, depart_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.depart.grpc.DepartResponse)) {
      return super.equals(obj);
    }
    com.depart.grpc.DepartResponse other = (com.depart.grpc.DepartResponse) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getDepartname()
        .equals(other.getDepartname());
    result = result && (getPriority()
        == other.getPriority());
    result = result && (getParentid()
        == other.getParentid());
    result = result && (getStatusId()
        == other.getStatusId());
    result = result && getDepartList()
        .equals(other.getDepartList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + DEPARTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDepartname().hashCode();
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getPriority();
    hash = (37 * hash) + PARENTID_FIELD_NUMBER;
    hash = (53 * hash) + getParentid();
    hash = (37 * hash) + STATUS_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStatusId();
    if (getDepartCount() > 0) {
      hash = (37 * hash) + DEPART_FIELD_NUMBER;
      hash = (53 * hash) + getDepartList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.depart.grpc.DepartResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.depart.grpc.DepartResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.depart.grpc.DepartResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.depart.grpc.DepartResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.depart.grpc.DepartResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.depart.grpc.DepartResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.depart.grpc.DepartResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.depart.grpc.DepartResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.depart.grpc.DepartResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.depart.grpc.DepartResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.depart.grpc.DepartResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.depart.grpc.DepartResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.depart.grpc.DepartResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.depart.grpc.DepartResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.depart.grpc.DepartResponse)
      com.depart.grpc.DepartResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.depart.grpc.DepartOuterClass.internal_static_com_depart_grpc_DepartResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.depart.grpc.DepartOuterClass.internal_static_com_depart_grpc_DepartResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.depart.grpc.DepartResponse.class, com.depart.grpc.DepartResponse.Builder.class);
    }

    // Construct using com.depart.grpc.DepartResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDepartFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0;

      departname_ = "";

      priority_ = 0;

      parentid_ = 0;

      statusId_ = 0;

      if (departBuilder_ == null) {
        depart_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
      } else {
        departBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.depart.grpc.DepartOuterClass.internal_static_com_depart_grpc_DepartResponse_descriptor;
    }

    public com.depart.grpc.DepartResponse getDefaultInstanceForType() {
      return com.depart.grpc.DepartResponse.getDefaultInstance();
    }

    public com.depart.grpc.DepartResponse build() {
      com.depart.grpc.DepartResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.depart.grpc.DepartResponse buildPartial() {
      com.depart.grpc.DepartResponse result = new com.depart.grpc.DepartResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.departname_ = departname_;
      result.priority_ = priority_;
      result.parentid_ = parentid_;
      result.statusId_ = statusId_;
      if (departBuilder_ == null) {
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          depart_ = java.util.Collections.unmodifiableList(depart_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.depart_ = depart_;
      } else {
        result.depart_ = departBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.depart.grpc.DepartResponse) {
        return mergeFrom((com.depart.grpc.DepartResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.depart.grpc.DepartResponse other) {
      if (other == com.depart.grpc.DepartResponse.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getDepartname().isEmpty()) {
        departname_ = other.departname_;
        onChanged();
      }
      if (other.getPriority() != 0) {
        setPriority(other.getPriority());
      }
      if (other.getParentid() != 0) {
        setParentid(other.getParentid());
      }
      if (other.getStatusId() != 0) {
        setStatusId(other.getStatusId());
      }
      if (departBuilder_ == null) {
        if (!other.depart_.isEmpty()) {
          if (depart_.isEmpty()) {
            depart_ = other.depart_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureDepartIsMutable();
            depart_.addAll(other.depart_);
          }
          onChanged();
        }
      } else {
        if (!other.depart_.isEmpty()) {
          if (departBuilder_.isEmpty()) {
            departBuilder_.dispose();
            departBuilder_ = null;
            depart_ = other.depart_;
            bitField0_ = (bitField0_ & ~0x00000020);
            departBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDepartFieldBuilder() : null;
          } else {
            departBuilder_.addAllMessages(other.depart_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.depart.grpc.DepartResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.depart.grpc.DepartResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object departname_ = "";
    /**
     * <code>string departname = 2;</code>
     */
    public java.lang.String getDepartname() {
      java.lang.Object ref = departname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string departname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDepartnameBytes() {
      java.lang.Object ref = departname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        departname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departname = 2;</code>
     */
    public Builder setDepartname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      departname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string departname = 2;</code>
     */
    public Builder clearDepartname() {
      
      departname_ = getDefaultInstance().getDepartname();
      onChanged();
      return this;
    }
    /**
     * <code>string departname = 2;</code>
     */
    public Builder setDepartnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      departname_ = value;
      onChanged();
      return this;
    }

    private int priority_ ;
    /**
     * <code>int32 priority = 3;</code>
     */
    public int getPriority() {
      return priority_;
    }
    /**
     * <code>int32 priority = 3;</code>
     */
    public Builder setPriority(int value) {
      
      priority_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 priority = 3;</code>
     */
    public Builder clearPriority() {
      
      priority_ = 0;
      onChanged();
      return this;
    }

    private int parentid_ ;
    /**
     * <code>int32 parentid = 4;</code>
     */
    public int getParentid() {
      return parentid_;
    }
    /**
     * <code>int32 parentid = 4;</code>
     */
    public Builder setParentid(int value) {
      
      parentid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 parentid = 4;</code>
     */
    public Builder clearParentid() {
      
      parentid_ = 0;
      onChanged();
      return this;
    }

    private int statusId_ ;
    /**
     * <code>int32 status_id = 5;</code>
     */
    public int getStatusId() {
      return statusId_;
    }
    /**
     * <code>int32 status_id = 5;</code>
     */
    public Builder setStatusId(int value) {
      
      statusId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status_id = 5;</code>
     */
    public Builder clearStatusId() {
      
      statusId_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.depart.grpc.Depart> depart_ =
      java.util.Collections.emptyList();
    private void ensureDepartIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        depart_ = new java.util.ArrayList<com.depart.grpc.Depart>(depart_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.depart.grpc.Depart, com.depart.grpc.Depart.Builder, com.depart.grpc.DepartOrBuilder> departBuilder_;

    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public java.util.List<com.depart.grpc.Depart> getDepartList() {
      if (departBuilder_ == null) {
        return java.util.Collections.unmodifiableList(depart_);
      } else {
        return departBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public int getDepartCount() {
      if (departBuilder_ == null) {
        return depart_.size();
      } else {
        return departBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public com.depart.grpc.Depart getDepart(int index) {
      if (departBuilder_ == null) {
        return depart_.get(index);
      } else {
        return departBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder setDepart(
        int index, com.depart.grpc.Depart value) {
      if (departBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartIsMutable();
        depart_.set(index, value);
        onChanged();
      } else {
        departBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder setDepart(
        int index, com.depart.grpc.Depart.Builder builderForValue) {
      if (departBuilder_ == null) {
        ensureDepartIsMutable();
        depart_.set(index, builderForValue.build());
        onChanged();
      } else {
        departBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder addDepart(com.depart.grpc.Depart value) {
      if (departBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartIsMutable();
        depart_.add(value);
        onChanged();
      } else {
        departBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder addDepart(
        int index, com.depart.grpc.Depart value) {
      if (departBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDepartIsMutable();
        depart_.add(index, value);
        onChanged();
      } else {
        departBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder addDepart(
        com.depart.grpc.Depart.Builder builderForValue) {
      if (departBuilder_ == null) {
        ensureDepartIsMutable();
        depart_.add(builderForValue.build());
        onChanged();
      } else {
        departBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder addDepart(
        int index, com.depart.grpc.Depart.Builder builderForValue) {
      if (departBuilder_ == null) {
        ensureDepartIsMutable();
        depart_.add(index, builderForValue.build());
        onChanged();
      } else {
        departBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder addAllDepart(
        java.lang.Iterable<? extends com.depart.grpc.Depart> values) {
      if (departBuilder_ == null) {
        ensureDepartIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, depart_);
        onChanged();
      } else {
        departBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder clearDepart() {
      if (departBuilder_ == null) {
        depart_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        departBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public Builder removeDepart(int index) {
      if (departBuilder_ == null) {
        ensureDepartIsMutable();
        depart_.remove(index);
        onChanged();
      } else {
        departBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public com.depart.grpc.Depart.Builder getDepartBuilder(
        int index) {
      return getDepartFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public com.depart.grpc.DepartOrBuilder getDepartOrBuilder(
        int index) {
      if (departBuilder_ == null) {
        return depart_.get(index);  } else {
        return departBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public java.util.List<? extends com.depart.grpc.DepartOrBuilder> 
         getDepartOrBuilderList() {
      if (departBuilder_ != null) {
        return departBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(depart_);
      }
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public com.depart.grpc.Depart.Builder addDepartBuilder() {
      return getDepartFieldBuilder().addBuilder(
          com.depart.grpc.Depart.getDefaultInstance());
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public com.depart.grpc.Depart.Builder addDepartBuilder(
        int index) {
      return getDepartFieldBuilder().addBuilder(
          index, com.depart.grpc.Depart.getDefaultInstance());
    }
    /**
     * <code>repeated .com.depart.grpc.Depart depart = 6;</code>
     */
    public java.util.List<com.depart.grpc.Depart.Builder> 
         getDepartBuilderList() {
      return getDepartFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.depart.grpc.Depart, com.depart.grpc.Depart.Builder, com.depart.grpc.DepartOrBuilder> 
        getDepartFieldBuilder() {
      if (departBuilder_ == null) {
        departBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.depart.grpc.Depart, com.depart.grpc.Depart.Builder, com.depart.grpc.DepartOrBuilder>(
                depart_,
                ((bitField0_ & 0x00000020) == 0x00000020),
                getParentForChildren(),
                isClean());
        depart_ = null;
      }
      return departBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.depart.grpc.DepartResponse)
  }

  // @@protoc_insertion_point(class_scope:com.depart.grpc.DepartResponse)
  private static final com.depart.grpc.DepartResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.depart.grpc.DepartResponse();
  }

  public static com.depart.grpc.DepartResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DepartResponse>
      PARSER = new com.google.protobuf.AbstractParser<DepartResponse>() {
    public DepartResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DepartResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DepartResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DepartResponse> getParserForType() {
    return PARSER;
  }

  public com.depart.grpc.DepartResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

