// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role.proto

package com.role.grpc;

public interface RoleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.role.grpc.Role)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 role_id = 4;</code>
   */
  int getRoleId();

  /**
   * <code>string role_name = 1;</code>
   */
  java.lang.String getRoleName();
  /**
   * <code>string role_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoleNameBytes();
}
