// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: power.proto

package com.power.grpc;

/**
 * Protobuf type {@code com.power.grpc.Power}
 */
public  final class Power extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.power.grpc.Power)
    PowerOrBuilder {
  // Use Power.newBuilder() to construct.
  private Power(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Power() {
    powerId_ = 0;
    powerName_ = "";
    powerUrl_ = "";
    parentId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Power(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            powerName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            powerUrl_ = s;
            break;
          }
          case 24: {

            parentId_ = input.readInt32();
            break;
          }
          case 32: {

            powerId_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.power.grpc.PowerOuterClass.internal_static_com_power_grpc_Power_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.power.grpc.PowerOuterClass.internal_static_com_power_grpc_Power_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.power.grpc.Power.class, com.power.grpc.Power.Builder.class);
  }

  public static final int POWER_ID_FIELD_NUMBER = 4;
  private int powerId_;
  /**
   * <code>int32 power_id = 4;</code>
   */
  public int getPowerId() {
    return powerId_;
  }

  public static final int POWER_NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object powerName_;
  /**
   * <code>string power_name = 1;</code>
   */
  public java.lang.String getPowerName() {
    java.lang.Object ref = powerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      powerName_ = s;
      return s;
    }
  }
  /**
   * <code>string power_name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPowerNameBytes() {
    java.lang.Object ref = powerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      powerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POWER_URL_FIELD_NUMBER = 2;
  private volatile java.lang.Object powerUrl_;
  /**
   * <code>string power_url = 2;</code>
   */
  public java.lang.String getPowerUrl() {
    java.lang.Object ref = powerUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      powerUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string power_url = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPowerUrlBytes() {
    java.lang.Object ref = powerUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      powerUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENT_ID_FIELD_NUMBER = 3;
  private int parentId_;
  /**
   * <code>int32 parent_id = 3;</code>
   */
  public int getParentId() {
    return parentId_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPowerNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, powerName_);
    }
    if (!getPowerUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, powerUrl_);
    }
    if (parentId_ != 0) {
      output.writeInt32(3, parentId_);
    }
    if (powerId_ != 0) {
      output.writeInt32(4, powerId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPowerNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, powerName_);
    }
    if (!getPowerUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, powerUrl_);
    }
    if (parentId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, parentId_);
    }
    if (powerId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, powerId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.power.grpc.Power)) {
      return super.equals(obj);
    }
    com.power.grpc.Power other = (com.power.grpc.Power) obj;

    boolean result = true;
    result = result && (getPowerId()
        == other.getPowerId());
    result = result && getPowerName()
        .equals(other.getPowerName());
    result = result && getPowerUrl()
        .equals(other.getPowerUrl());
    result = result && (getParentId()
        == other.getParentId());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POWER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPowerId();
    hash = (37 * hash) + POWER_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getPowerName().hashCode();
    hash = (37 * hash) + POWER_URL_FIELD_NUMBER;
    hash = (53 * hash) + getPowerUrl().hashCode();
    hash = (37 * hash) + PARENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getParentId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.power.grpc.Power parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.grpc.Power parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.grpc.Power parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.grpc.Power parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.grpc.Power parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.power.grpc.Power parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.power.grpc.Power parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.power.grpc.Power parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.power.grpc.Power parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.power.grpc.Power parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.power.grpc.Power parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.power.grpc.Power parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.power.grpc.Power prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.power.grpc.Power}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.power.grpc.Power)
      com.power.grpc.PowerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.power.grpc.PowerOuterClass.internal_static_com_power_grpc_Power_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.power.grpc.PowerOuterClass.internal_static_com_power_grpc_Power_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.power.grpc.Power.class, com.power.grpc.Power.Builder.class);
    }

    // Construct using com.power.grpc.Power.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      powerId_ = 0;

      powerName_ = "";

      powerUrl_ = "";

      parentId_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.power.grpc.PowerOuterClass.internal_static_com_power_grpc_Power_descriptor;
    }

    public com.power.grpc.Power getDefaultInstanceForType() {
      return com.power.grpc.Power.getDefaultInstance();
    }

    public com.power.grpc.Power build() {
      com.power.grpc.Power result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.power.grpc.Power buildPartial() {
      com.power.grpc.Power result = new com.power.grpc.Power(this);
      result.powerId_ = powerId_;
      result.powerName_ = powerName_;
      result.powerUrl_ = powerUrl_;
      result.parentId_ = parentId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.power.grpc.Power) {
        return mergeFrom((com.power.grpc.Power)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.power.grpc.Power other) {
      if (other == com.power.grpc.Power.getDefaultInstance()) return this;
      if (other.getPowerId() != 0) {
        setPowerId(other.getPowerId());
      }
      if (!other.getPowerName().isEmpty()) {
        powerName_ = other.powerName_;
        onChanged();
      }
      if (!other.getPowerUrl().isEmpty()) {
        powerUrl_ = other.powerUrl_;
        onChanged();
      }
      if (other.getParentId() != 0) {
        setParentId(other.getParentId());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.power.grpc.Power parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.power.grpc.Power) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int powerId_ ;
    /**
     * <code>int32 power_id = 4;</code>
     */
    public int getPowerId() {
      return powerId_;
    }
    /**
     * <code>int32 power_id = 4;</code>
     */
    public Builder setPowerId(int value) {
      
      powerId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 power_id = 4;</code>
     */
    public Builder clearPowerId() {
      
      powerId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object powerName_ = "";
    /**
     * <code>string power_name = 1;</code>
     */
    public java.lang.String getPowerName() {
      java.lang.Object ref = powerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        powerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string power_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPowerNameBytes() {
      java.lang.Object ref = powerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        powerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string power_name = 1;</code>
     */
    public Builder setPowerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      powerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string power_name = 1;</code>
     */
    public Builder clearPowerName() {
      
      powerName_ = getDefaultInstance().getPowerName();
      onChanged();
      return this;
    }
    /**
     * <code>string power_name = 1;</code>
     */
    public Builder setPowerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      powerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object powerUrl_ = "";
    /**
     * <code>string power_url = 2;</code>
     */
    public java.lang.String getPowerUrl() {
      java.lang.Object ref = powerUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        powerUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string power_url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPowerUrlBytes() {
      java.lang.Object ref = powerUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        powerUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string power_url = 2;</code>
     */
    public Builder setPowerUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      powerUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string power_url = 2;</code>
     */
    public Builder clearPowerUrl() {
      
      powerUrl_ = getDefaultInstance().getPowerUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string power_url = 2;</code>
     */
    public Builder setPowerUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      powerUrl_ = value;
      onChanged();
      return this;
    }

    private int parentId_ ;
    /**
     * <code>int32 parent_id = 3;</code>
     */
    public int getParentId() {
      return parentId_;
    }
    /**
     * <code>int32 parent_id = 3;</code>
     */
    public Builder setParentId(int value) {
      
      parentId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 parent_id = 3;</code>
     */
    public Builder clearParentId() {
      
      parentId_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.power.grpc.Power)
  }

  // @@protoc_insertion_point(class_scope:com.power.grpc.Power)
  private static final com.power.grpc.Power DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.power.grpc.Power();
  }

  public static com.power.grpc.Power getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Power>
      PARSER = new com.google.protobuf.AbstractParser<Power>() {
    public Power parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Power(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Power> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Power> getParserForType() {
    return PARSER;
  }

  public com.power.grpc.Power getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

