// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: power.proto

package com.power.grpc;

public interface PowerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.power.grpc.Power)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 power_id = 4;</code>
   */
  int getPowerId();

  /**
   * <code>string power_name = 1;</code>
   */
  java.lang.String getPowerName();
  /**
   * <code>string power_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getPowerNameBytes();

  /**
   * <code>string power_url = 2;</code>
   */
  java.lang.String getPowerUrl();
  /**
   * <code>string power_url = 2;</code>
   */
  com.google.protobuf.ByteString
      getPowerUrlBytes();

  /**
   * <code>int32 parent_id = 3;</code>
   */
  int getParentId();
}
