// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager.proto

package com.manager.grpc;

public interface ManagerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.manager.grpc.ManagerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 role_id = 7;</code>
   */
  java.util.List<java.lang.Integer> getRoleIdList();
  /**
   * <code>repeated int32 role_id = 7;</code>
   */
  int getRoleIdCount();
  /**
   * <code>repeated int32 role_id = 7;</code>
   */
  int getRoleId(int index);

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>int32 status_id = 4;</code>
   */
  int getStatusId();

  /**
   * <code>string token = 6;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 6;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string introduction = 9;</code>
   */
  java.lang.String getIntroduction();
  /**
   * <code>string introduction = 9;</code>
   */
  com.google.protobuf.ByteString
      getIntroductionBytes();

  /**
   * <code>string avatar = 8;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 8;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <code>repeated .com.manager.grpc.Manager manager = 5;</code>
   */
  java.util.List<com.manager.grpc.Manager> 
      getManagerList();
  /**
   * <code>repeated .com.manager.grpc.Manager manager = 5;</code>
   */
  com.manager.grpc.Manager getManager(int index);
  /**
   * <code>repeated .com.manager.grpc.Manager manager = 5;</code>
   */
  int getManagerCount();
  /**
   * <code>repeated .com.manager.grpc.Manager manager = 5;</code>
   */
  java.util.List<? extends com.manager.grpc.ManagerOrBuilder> 
      getManagerOrBuilderList();
  /**
   * <code>repeated .com.manager.grpc.Manager manager = 5;</code>
   */
  com.manager.grpc.ManagerOrBuilder getManagerOrBuilder(
      int index);
}
