// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager.proto

package com.manager.grpc;

public interface ManagerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.manager.grpc.Manager)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string username = 2;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 3;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string token = 6;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 6;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string introduction = 7;</code>
   */
  java.lang.String getIntroduction();
  /**
   * <code>string introduction = 7;</code>
   */
  com.google.protobuf.ByteString
      getIntroductionBytes();

  /**
   * <code>string avatar = 8;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 8;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();
}
