// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manager_role.proto

package com.manager_role.grpc;

public interface MRResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.manager_role.grpc.MRResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 4;</code>
   */
  int getId();

  /**
   * <code>int32 role_id = 1;</code>
   */
  int getRoleId();

  /**
   * <code>int32 manager_id = 2;</code>
   */
  int getManagerId();

  /**
   * <code>repeated .com.manager_role.grpc.MR mr = 5;</code>
   */
  java.util.List<com.manager_role.grpc.MR> 
      getMrList();
  /**
   * <code>repeated .com.manager_role.grpc.MR mr = 5;</code>
   */
  com.manager_role.grpc.MR getMr(int index);
  /**
   * <code>repeated .com.manager_role.grpc.MR mr = 5;</code>
   */
  int getMrCount();
  /**
   * <code>repeated .com.manager_role.grpc.MR mr = 5;</code>
   */
  java.util.List<? extends com.manager_role.grpc.MROrBuilder> 
      getMrOrBuilderList();
  /**
   * <code>repeated .com.manager_role.grpc.MR mr = 5;</code>
   */
  com.manager_role.grpc.MROrBuilder getMrOrBuilder(
      int index);

  /**
   * <code>int32 status_id = 6;</code>
   */
  int getStatusId();
}
