// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_power.proto

package com.role_power.grpc;

public interface RPOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.role_power.grpc.RP)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 4;</code>
   */
  int getId();

  /**
   * <code>int32 role_id = 1;</code>
   */
  int getRoleId();

  /**
   * <code>int32 power_id = 2;</code>
   */
  int getPowerId();
}
