// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Discovery.proto

package com.discovery.grpc;

public interface DiscoveryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.discovery.grpc.Discovery)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string itemname = 2;</code>
   */
  java.lang.String getItemname();
  /**
   * <code>string itemname = 2;</code>
   */
  com.google.protobuf.ByteString
      getItemnameBytes();

  /**
   * <code>string itemurl = 3;</code>
   */
  java.lang.String getItemurl();
  /**
   * <code>string itemurl = 3;</code>
   */
  com.google.protobuf.ByteString
      getItemurlBytes();

  /**
   * <code>int32 itempriority = 4;</code>
   */
  int getItempriority();

  /**
   * <code>int32 status = 5;</code>
   */
  int getStatus();

  /**
   * <code>int32 created = 6;</code>
   */
  int getCreated();

  /**
   * <code>int32 updated = 7;</code>
   */
  int getUpdated();
}
